coserv = {
  &(artifact-type: 0) => artifact-type
  &(profile: 1) => profile-type
  &(environment-selector: 2) => environment-selector-map
}

artifact-type = &(endorsed-values: 0)
                / &(trust-anchors: 1)
                / &(reference-values: 2)

profile-type = oid-type / ~uri
