environment-selector-map = { selector }

selector //= ( &(class: 0) => [
  + ( class-map, ? [ + measurement-map ] )
] )

selector //= ( &(instance: 1) => [
  + ( $instance-id-type-choice, ? [ + measurement-map ] )
] )

selector //= ( &(group: 2) => [
  + ( $group-id-type-choice, ? [ + measurement-map ] )
] )
